config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clientes
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :conta, :senha, :email, :mensagem)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :conta %>
    <%= form.text_field :conta %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.password_field :senha %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mensagem %>
    <%= form.text_field :mensagem %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar Cliente" %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Conta</th>
      <th>Senha</th>
      <th>Email</th>
      <th>Mensagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.conta %></td>
        <td><%= cliente.senha %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.mensagem %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_cliente_path %>
<%= link_to 'Sair', destroy_user_session_path, method: :delete %>

app/views/clientes/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Conta:</strong>
  <%= @cliente.conta %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @cliente.senha %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Mensagem:</strong>
  <%= @cliente.mensagem %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioGerencial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Seja bem-vindo Gerente!</h1>

<ul>
	<li><%= link_to "Entrar no sistema", clientes_path %></li>
</ul>